-- MySQL에서는 DATE_ADD와 CURDATE() 함수를 사용
INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10001, 'gemini_user', 'Learn JPA and MySQL', DATE_ADD(CURDATE(), INTERVAL 1 YEAR), false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10002, 'gemini_user', 'Master Spring Boot with MySQL', DATE_ADD(CURDATE(), INTERVAL 2 YEAR), false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10003, 'another_user', 'Practice Coding with MySQL', DATE_ADD(CURDATE(), INTERVAL 6 MONTH), false);